Repository fdnd-agency/deloitte, pull requests merged in 2024-10, with the labels that each got.

#48 26 overzichtspagina
  .gitignore
  src/lib/general-info.svelte
  src/lib/mobility-options.svelte
  src/routes/+page.svelte
  src/routes/overview/+page.js
  src/routes/overview/+page.svelte
  src/styles/overview.css
Labels: must have, sprint 14, analyseren, bouwen, ontwerpen

#78 CW - profile
  src/routes/profile/+page.svelte
Labels: integreren

#76 CW - adjusted layout
  src/routes/+layout.svelte
Labels: integreren

#74 73 login pagina iteration2
  src/routes/Inlog/+page.svelte
  src/routes/inlog/+page.svelte
Labels: analyseren, bouwen, integreren, testen, taken
